### ISSUE TITLE
Screen glitched 

### ISSUE THREAD

**Issue by NML32** [MrX-8B/MiSTer-Arcade-NinjaKun#2]
The screen glitched after dying and cleared up after loading the next level. 
You can see the glitch around 2:18 in the video. 
This has only happened one time but I thought I should still report it. 
https://youtu.be/BuNSoEVcsDc

**Comment by MrX-8B** [comment]
Thank you for bug report.
There seems to be a problem with the synchronization of the two CPUs.
It will be fixed in the next release.

**Comment by MrX-8B** [comment]
The glitch is no longer visible in the 20191023 version with fixed video timing, so it has been fixed.

**Comment by wwark** [comment]
Hi,
Sorry, the glitch is still present.
![IMG_20191112_070128](https://user-images.githubusercontent.com/469461/68646228-d5a6fa00-051a-11ea-8b35-7113ff489afb.jpg)

How to reproduce ?
Let the demo run (not add any coins) and the issue happen time to time but I don't know the frequency.

I have a Mister with 128SD Ram if this information is needed and last update from official repository

Thanks for the fix!

**Comment by MrX-8B** [comment]
Thank you for report.
Because it does not reproduce easily at hand, it is difficult to judge whether it is fixed or not.
I know it's still going to happen.

**Comment by wwark** [comment]
Yes it is a very rare case so difficult to fix. On my personal project i have time to time similar issue ....
Do you have also this issue on your personal board or it happens just on Mister side ?
Thank you !

**Comment by MrX-8B** [comment]
I've never happened on my own board.
The chip that was working is different from MiSTer, so it may be a timing problem.

**Comment by gyurco** [comment]
Maybe it's due to the large number of clocks used. Have you considered to work with a single main clock and clock-enables instead of vast number of generated clocks? I've already converted some of your cores with great success.
https://github.com/Gehstock/Mist_FPGA/tree/master/Arcade_MiST/Atari%20Tetris/rtl
https://github.com/Gehstock/Mist_FPGA/tree/master/Arcade_MiST/Namco%20Mappy%20Hardware/rtl
https://github.com/Gehstock/Mist_FPGA/tree/master/Arcade_MiST/Konami%20Green%20Beret%20Hardware/rtl

**Comment by MrX-8B** [comment]
Thank you for your advice.
I would like to make use of it in the future.
